// Generated by https://quicktype.io

declare interface Page {
  id: number
  status: number
  sort: null
  title: string
  img: Img
  content: string
  order: number
  slug: string
  fullImgUrl: string
}

declare interface Img {
  meta: Meta
  data: Data
}

declare interface Data {
  id: number
  status: number
  name: string
  title: string
  location: string
  caption: string
  type: string
  charset: string
  tags: string
  width: number
  height: number
  size: number
  embed_id: null
  user: number
  date_uploaded: string
  storage_adapter: string
  url: string
  thumbnail_url: string
  old_thumbnail_url: string
  html: null
}

declare interface Meta {
  table: string
  type: string
}
