// Generated by https://quicktype.io

declare interface Program {
  id: number
  status: number
  sort: null
  name: string
  requirements: string
  sample_track: string
  desc: string
  outcomes: string
  concentra: string
  slug: string
  subtitle: string
  order: number
}
